### PR TITLE
v2-a104 fixes

### PR DESCRIPTION
**Pull request by mmikeww**
@hoppfrosch on the forums you said you would be using this new fix from lexikos in v2 a104+

Can you confirm whether its working fine for you, and if you think its ready to merge?

related issue #28

### CODE REVIEW

**Comment by hoppfrosch** [comment]
Lexikos' fix just fixes the base module - the Window-module (Window.ahk) is still unfixed. Due to lack of time I didn't manage to fix this module yet

**Comment by mmikeww** [comment]
looks like the base Yunit is even broken now, since a106 removed the `new` operator

**Comment by hoppfrosch** [comment]
Updating from a103 to a107 is a lot of work ... that's why I am still hestating to do it - there have been too many incombatible breaking changes recently. I think it's better waiting until consolidation ...

**Comment by mmikeww** [comment]
i've merged in Lexikos' changes and also made new updates myself for v2a108 for the base Yunit and the Output Modules

**Pull request merged**
